### ISSUE TITLE
Leave messages for people

### ISSUE THREAD

**Issue by cburschka** [sylae/ligrev#12]
It'd be pretty awesome if you could do `:tell $user ...` and Ligrev would store the message until $user next logs in.

A public `:tell` would result in a public message; `/msg Ligrev :tell` would result in a whisper.

**Comment by sylae** [comment]
[XEP-0160](http://xmpp.org/extensions/xep-0160.html) appears to be a good solution to handling this natively, however clients would need to be more obvious about having received an offline message. Currently cadence treats them as a regular dmsg that appears after room join, and pidgin just pops it up in a window. Cadence uses the 'real' timestamp rather than when it was initially sent, and iirc so does pidgin.

As it is, Ligrev would be a good intermediary for servers not supporting XEP-0160.

**Comment by sylae** [comment]
Fuck, I forgot to do a commit message.

Uhhh...

sylae closed this issue from commit 39de047e4ca46f9c37c3444c812b40dea4a03caa

(nobody will ever notice!
