### ISSUE TITLE
:tell fails for users in another room.

### ISSUE THREAD

**Issue by cburschka** [sylae/ligrev#31]
When Ligrev is in two rooms (eg `rp` and `lounge`), you can't `:tell X` in `lounge` if user X is online and in `rp`.

Ideally, Ligrev should accept the message and deliver it instantly in that case.

**Comment by cburschka** [comment]
Note that once Ligrev formats users with the right data attributes, clicking on the sender will put `/dmsg <JID>` into the text field, so you can then communicate directly without sending everything through :tell.

**Comment by sylae** [comment]
This is by design. The intent is that, if a user is online already, they should use `/dmsg` to contact the user themselves. This way a user cannot simply 'bypass' XMPP blocklist features such as [XEP-0191](http://xmpp.org/extensions/xep-0191.html) and [XEP-0016](http://xmpp.org/extensions/xep-0016.html).

Perhaps once :tell blocking (#19) is implemented, this could be a potential feature, but as it is, I don't see any reason to reinvent the `/dmsg` wheel.
